[package]
name = "lumen-core"
version = "0.1.0"
edition = "2021"
authors = ["Lumen Team"]
description = "Core functionality for Lumen compiler"
license = "MIT"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
anyhow = "1.0" 